### ISSUE TITLE
WB-MRGBW-D Не отражается  яркость в 2W+W+W режиме

### ISSUE THREAD

**Issue by lin4in** [4mr/wb-engine#1]
Добрый день!
Диммер W+W+W+W пробрасывается корректно с управлением яркостью на каждом канале.
Диммер светодиодных лент работает в режиме 2*W+W+W.  Сдвоенный канал пробрасывается в HA в виде выключателя без яркости. 

Настройка режима работы диммера в WB:
![image](https://user-images.githubusercontent.com/809501/200138555-290a069a-8288-4470-ab5f-c1560657e988.png)

Режим управления яркостью в WB:
![image](https://user-images.githubusercontent.com/809501/200138220-dc9cb33e-126b-41af-aa56-1ce21c7c13db.png)

Wb-engine:
![image](https://user-images.githubusercontent.com/809501/200138808-37a082c5-df18-4f7d-8208-230583972dbb.png)

Отображение в НА без возможности задать яркость:
![image](https://user-images.githubusercontent.com/809501/200138718-1827cac1-2992-48e2-a722-8c647211bbe4.png)

https://wirenboard.com/ru/product/WB-MRGBW-D/

**Comment by lin4in** [comment]
MR6C, MRCU  - пробросились корректно. Спасибо!
MDM в режиме изменения яркости корректно. В режиме ключа **остается** ползунок яркости, но не влияет на яркость (не критично)

**Comment by lin4in** [comment]
Если правильно понял, то regexp не проходит из-за множественного числа /devices/wb-mrgbw-d-fw3_81/controls/Channel**s** 1_2 (B_R)

Предлагаю расширить regexp в wb-engine.devices.conf: [^Channels? [0-9\_]{1,3}](https://regex101.com/r/Y7KWJp/1)

**Comment by 4mr** [comment]
Добавил исправление. Спасибо.

**Comment by 4mr** [comment]
> MDM в режиме изменения яркости корректно. В режиме ключа **остается** ползунок яркости, но не влияет на яркость (не критично)

В ВБ тоже остается ползунок яркости. По топикам MQTT не получается определить в каком режиме работает канал... можно сделать опцию для выбора режима в настройках, но нужно ли?

**Comment by lin4in** [comment]
Спасибо. Удалил устройство из HA и еще раз save в wb-engine
