### ISSUE TITLE
Скрипт термостата enabled_by_default

### ISSUE THREAD

**Issue by Destix** [4mr/wb-engine#11]
При любом обновлении конфигурации wb-engine заново прописываются discovery топики HA
HA включает все термостаты, потому что если параметр enabled_by_default: (Flag which defines if the entity should be enabled when first added.) опущен, то он (optional, default: true)
Логичнее добавить его в положение false, либо предоставить возможно выбора пользователю.

**Comment by 4mr** [comment]
Термостаты включаются по умолчанию, если стоит галочка в "Enable Script" , уберите и не будут включаться. 
Вообще по задумке при старте скрипт считывает через wb-rules предыдущее состояние, но оно не всегда там есть.

**Comment by Destix** [comment]
Мой косяк. Так и есть.
А опция enabled_by_default: отвечает за видимость сущности в HA (может еще быть hidden или disabled)
