### ISSUE TITLE
MQTT timeout при большом количестве устройств

### ISSUE THREAD

**Issue by Marko298** [4mr/wb-engine#12]
Пытался запустить на своей системе, не смог даже открыть конфигурацию. Прилетает MQTT timeout. Если посмотреть в devtools, то оно очень долго присылает конфиг по одной строчке.

**Comment by 4mr** [comment]
Большое количество устройств это сколько?
Попробуйте увеличить readTimeout (по умолчанию 60) в файле /usr/bin/wb-engine-helper.

**Comment by Marko298** [comment]
38 устройств.
с таймом поиграюсь, а возможно как-то конфиг уменьшить? ждать 2-3 мин чтобы конфиг открыть, так себе решение

**Comment by Marko298** [comment]
Контроллер WB7/64. Без пакета за 14с открывается wb-mqtt-serial.conf

**Comment by Marko298** [comment]
С пакетом ~20c. А конфиг wb-engine не открывается

**Comment by 4mr** [comment]
Пакет никак не влияет на открытие wb-mqtt-serial.conf. 
Запустите по ssh команду:
`time cat /etc/wb-rules/wb-engine.conf | /usr/bin/wb-engine-helper --json > /dev/null`
У меня отрабатывает за 2.5сек.

**Comment by Marko298** [comment]
Ошыбка и зависло

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 2936, in _packet_handle
    return self._handle_publish()
  File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 3216, in _handle_publish
    self._handle_on_message(message)
  File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "/usr/bin/wb-engine-helper", line 82, in mqtt_on_message
    parseWB(topicParts, msg)
  File "/usr/bin/wb-engine-helper", line 118, in parseWB
    if ('controls' not in devices[deviceName]):
KeyError: 'system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3'`

**Comment by 4mr** [comment]
Вот поэтому и вылетает, не может разобрать топик от networks.
Можете показать содержимое топиков MQTT, команда:
`mosquitto_sub -v -t '/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/#'`

**Comment by Marko298** [comment]
```

root@wirenboard-A7TPFAWI:~# mosquitto_sub -v -t '/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/#'
/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/controls/Active/meta/type switch
/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/controls/Active/meta/order 4
/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/controls/Active/meta/readonly 1
/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/controls/Address/meta/order 7
/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/controls/Address/meta/readonly 1
/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/controls/Address/meta/type text
/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/controls/Connectivity/meta/readonly 1
/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/controls/Connectivity/meta/type switch
/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/controls/Connectivity/meta/order 8
/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/controls/Device/meta/type text
/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/controls/Device/meta/order 5
/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/controls/Device/meta/readonly 1
/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/controls/Name/meta/type text
/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/controls/Name/meta/order 1
/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/controls/Name/meta/readonly 1
/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/controls/State/meta/type text
/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/controls/State/meta/order 6
/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/controls/State/meta/readonly 1
/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/controls/Type/meta/order 3
/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/controls/Type/meta/readonly 1
/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/controls/Type/meta/type text
/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/controls/UUID/meta/readonly 1
/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/controls/UUID/meta/type text
/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/controls/UUID/meta/order 2
/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/controls/UpDown/meta/order 9
/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/controls/UpDown/meta/readonly 0
/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/controls/UpDown/meta/type pushbutton

```

**Comment by Marko298** [comment]
думаю связано с новым NetworkManager

**Comment by 4mr** [comment]
> думаю связано с новым NetworkManager

Похоже на это, но у меня с ним открывается без ошибок... 
А что это за соединение, почему то нету его названия, должен быть топик вида:
> /devices/system__networks__91f1c71d-2d97-4675-886f-ecbe52b8451e/meta/name Network Connection wb-eth0

Но у Вас его почему то нет. Может его удалить ?

**Comment by 4mr** [comment]
Целиком удалить весь "/devices/system__networks__f84324ce-fb6b-4c37-a6eb-1fb768164fb3/" через MQTT Explorer

**Comment by Marko298** [comment]
думаю tailscale создал

**Comment by 4mr** [comment]
> думаю tailscale создал

Должно быть название, а это похоже на чтото что создал NM и создал не полностью, т.к. нету топика /meta/name

**Comment by Marko298** [comment]
Удалил топики, заработало, но они сами создадутся через 60с. Я думаю что это tailscale создает когда либо поднимает туннель или когда использую tailscale ssh

**Comment by Marko298** [comment]
Можно как-то игнорировать эти топики?

**Comment by 4mr** [comment]
> Удалил топики, заработало, но они сами создадутся через 60с. Я думаю что это tailscale создает когда либо поднимает туннель или когда использую tailscale ssh

Топик создался? tailscale не должен его создавать, эти топики создает "wb-connection-manager", вроде бы он не должен просто так сам создавать заново топики такие.

**Comment by Marko298** [comment]
Пока нет. Буду смотреть дальше.

**Comment by 4mr** [comment]
Будем надеяться это был артефакт старый в MQTT, который больше не появится.

**Comment by Marko298** [comment]
Плюс.
Вопрос на другую тему: можно как-то включить ХА для все устройств одним кликом?

**Comment by 4mr** [comment]
> Вопрос на другую тему: можно как-то включить ХА для все устройств одним кликом?

Нету такого, обычно оно и не нужно, у устройств много каналов, не все нужны в ХА... Такое и не реализовать в интерфейсе/редакторе этом.

**Comment by mark-b-ab** [comment]
Принял. Спасибо! Я тогда закрою issue, если случиться снова, открою еще раз.

**Comment by Marko298** [comment]
Снова проблема с таймаутом

![CleanShot 2023-08-02 at 16 25 59](https://github.com/4mr/wb-engine/assets/12628139/86fa585d-743e-4e52-98ed-2c12df366fe6)

![CleanShot 2023-08-02 at 16 26 58](https://github.com/4mr/wb-engine/assets/12628139/52d2958e-ebbc-4b0e-9751-b631c2a8c867)
