### ISSUE TITLE
После обновления контроллера WB7 - не работает, выдаёт ошибку, подробности внутри

### ISSUE THREAD

**Issue by Cifrum** [4mr/wb-engine#13]
после обновления контроллера:
Wirenboard release wb-2304 (as stable), target wb7/bullseye
и установки с нуля wb-engine не работает. при выборе пункта Настройки-Конфигурационные файлы-WB-Engine отображает ошибку:
![image](https://github.com/4mr/wb-engine/assets/98122678/687aff4b-a96c-4edf-8b51-cbb3c9626107)

Если зайти в Правила и открыть правило wb-engine, то ошибка такая:
![image](https://github.com/4mr/wb-engine/assets/98122678/66080e6d-6e69-47a0-9bcf-2ccf8eb0e60a)

P.S. Извиняюсь, что тут запостил, но имхо так будет лучше исправить, не все увидят проблему на форуме.
P.S.2 Правка в /etc/mosquitto/mosquitto.conf выставить persistence = false помогает.

**Comment by 4mr** [comment]
Исправлено
