### ISSUE TITLE
Отображение названия в HA - The naming of MQTT entities changes

### ISSUE THREAD

**Issue by efendizadeh** [4mr/wb-engine#15]
В cвязи с изменением конвенции названия отображается некорректно на стороне HA

https://community.home-assistant.io/t/discovered-entities-with-a-name-that-starts-with-the-device-name/598730/2
https://developers.home-assistant.io/blog/2023-057-21-change-naming-mqtt-entities/

<img width="664" alt="Screen Shot 2023-08-21 at 02 48 06 1" src="https://github.com/4mr/wb-engine/assets/7306284/203668ee-5308-4223-b9ae-bd20e47f9fbb">

<img width="391" alt="Screen Shot 2023-08-21 at 02 49 07" src="https://github.com/4mr/wb-engine/assets/7306284/7dd52c4a-0225-4a78-a0e1-3ef7f18c7685">

Лечится тем что выбирается **Custom device name** но оставляется пустым

<img width="971" alt="Screen Shot 2023-08-21 at 02 52 19" src="https://github.com/4mr/wb-engine/assets/7306284/bf8b636a-33d0-404a-96f2-54a9b142b24a">

**Comment by efendizadeh** [comment]
Ошибся
не лечится 

<img width="911" alt="Screen Shot 2023-08-21 at 03 08 11" src="https://github.com/4mr/wb-engine/assets/7306284/ba8da90c-5b06-4dc5-80c9-b1ca697b6d8d">

**Comment by 4mr** [comment]
Привет.

Пока непонятно как исправить это, самый простой путь указать нужный name через HA, он тогда ставит friendly_name какой указываешь. Через MQTT Discovert friendly_name не меняется.

Иначе он всегда добавляет device.name, зачем так решили сделать непонятно...
> The friendly_name state attribute is generated by combining then entity name with the device name as follows:
> The entity is not a member of a device: friendly_name = entity.name
> The entity is a member of a device and entity.name is not None: friendly_name = f"{device.name} {entity.name}"
> The entity is a member of a device and entity.name is None: friendly_name = f"{device.name}"

**Comment by efendizadeh** [comment]
Может попробуем без секции device? Тогда тогда получится **entity is not a member of a device**.

без секции:
_device:
  identifiers: wb-led_105
  manufacturer: WirenBoard
  model: wb-led [wb-modbus]
  name: WB-LED 105_
