### ISSUE TITLE
Feature request: Настройка инверсии для бинарных датчиков WB-GPIO

### ISSUE THREAD

**Issue by sd-em** [4mr/wb-engine#17]
К модулю дискретных входов WB подключены дачтики открытия двери таким образом, что при замыкании цепи (дверь закрыта) значение дискретного входа = True. 
Сейчас в home assistant значение прокидывается так:
        {
            "topic": "/devices/wb-gpio/controls/EXT1_IN1",
            "value_template": "{{ False if value == '' else True }}",
            "payload_not_available": false,
            "payload_available": true
        }

При установке в home assistant типа "Дверь" для датчика, при значении True отображается состояние "Открыта", что не соответствует факту.
Предлагаю сделать опцию инвертирования значения, передаваемого в Home Assisttant.

**Comment by 4mr** [comment]
У меня нет таких устройств, для реализации мне нужно пример MQTT топиков и их значения.

**Comment by sd-em** [comment]
Вот пример топиков:
/devices/wb-gpio/controls/EXT1_IN1 - значение 1 - в моём случае с нормально-открытым герконом соответствует замкнутому контакту, т.е. дверь закрыта
/devices/wb-gpio/controls/EXT1_IN2 - значение 0 - в моём случае соответствует открой двери
Сейчас в home assistant передаётся binary_sensor.wb_gpio_ext1_in1 со значением true, а binary_sensor.wb_gpio_ext1_in2 - false, что в случае установке этим сущностям типа "Дверь" приводит к противоположному от фактического отображению статуса
Т.к. герконы бывают как нормально-закрытые, так и нормально-открытые, то инверсия должна быть именно опцией

<img width="566" alt="image" src="https://github.com/user-attachments/assets/c7299964-0b64-4ca6-8b36-05bd0a158a87">

**Comment by 4mr** [comment]
Добавил [binary_sensor/binary_sensor_inversed](https://github.com/4mr/wb-engine/commit/220a0049ce77174a16eb1442b953929647302248)
