### ISSUE TITLE
A1_IN_Total не пробрасывается в HA

### ISSUE THREAD

**Issue by lin4in** [4mr/wb-engine#2]
A1_IN_Total, A2_IN_Total (учет с водосчетчиков) не отображаются в HA
![image](https://user-images.githubusercontent.com/809501/200141144-7459f784-5583-4f31-a1de-242592f17211.png)
![image](https://user-images.githubusercontent.com/809501/200141184-ba5559c0-d7db-4cce-b9ca-e4f817232379.png)

Wb-rules:
![image](https://user-images.githubusercontent.com/809501/200141217-85f0cbcc-1c22-4303-885e-3e445918fae4.png)

В конфиге wb-engine.conf настройка активировалась:
```
{
                    "custom_name": "\u0420\u0430\u0441\u0445\u043e\u0434 \u0445\u043e\u043b\u043e\u0434\u043d\u043e\u0439 \u0432\u043e\u0434\u044b",
                    "id": "A1_IN_total",
                    "enabled": true,
                    "hass_id": "A1_in_total",
                    "name": "A1_IN_total"
                },
                {
```

**Comment by 4mr** [comment]
Добавил два новых типа:
- water_consumption
- water_flow

Отображается корректно теперь:
![image](https://user-images.githubusercontent.com/78191171/200152441-e43c4235-edf7-4762-a03e-ac35f339f3e5.png)

И появляется в панели "Энергия" для учета расхода воды.
