### ISSUE TITLE
Пауза для relay_direction DO-R10R-4 

### ISSUE THREAD

**Issue by G1K** [4mr/wb-engine#25]
Мне кажется чтобы соблюсти рекомендации для DO-R10R-4
https://wirenboard.com/wiki/WBIO-DO-R10R-4_Relay_Module_For_Roller_Shutter
> Чтобы избежать этого, перед переключением направления надо отключать нагрузку. Рекомендуем следующий алгоритм:
> 
> выключите привод (контрол *_ON);
> выдержите паузу не менее 0.5 с;
> переключите направление (контрол *_DIR);
> включите привод ( контрол *_ON).

Нужно здесь еще 1 таймер добавить на 500 мс и дожидаться переключения реле направления если оно не в том направлении что требуется для движения. Сейчас подряд оба устанавливается без паузы. Пауза есть только если реле движения было включено.
https://github.com/4mr/wb-engine/blob/a3f45dc898175526db6543cb9208b71648e2d866/wb-engine-module.js#L523

**Comment by 4mr** [comment]
> Я просто думаю может стоит дожидаться окончания замыкания R2, а уже после отправлять на замыкание R1?

Я так понимаю dev[name] = true работает в синхронном режиме, надо код wb-rules смотреть или в поддержке спросить для уверенности.

**Comment by 4mr** [comment]
Добавил задержку в 100мс после смены направления
