### ISSUE TITLE
Датчик давления из WB 

### ISSUE THREAD

**Issue by ilttkolosov** [4mr/wb-engine#26]
Добрый день, 
На WB 7 создано виртуальное устройство, в котором собираются датчики давления (водопровод, магистраль отопления и т.д). Тип данных в MQTT топике на WB - "pressure", ед. измерения "bar", значения есть (берутся с датчика и меняются).
![image](https://github.com/user-attachments/assets/c0e07d2b-989c-4033-b830-91a4c5ff6f4a)
![image](https://github.com/user-attachments/assets/068e25fc-1e3f-452b-b6ff-18d696687501)
Есть нюанс, что для отображения значения с датчика в типе данных "pressure" на виртуальном устройстве, необходимо было число преобразовать в текст. Правило формирования данных на WB у меня выглядит так:

```
defineVirtualDevice("PressSensors", {
    title: "Датчики давления",
    cells: {
    	Press2: {
    	    type: "pressure",
    	    value: "0",
            readonly: true,          
            title: "Датчик 2"      
        },
        Test: {
    	    type: "text",
    	    value: "test",
            readonly: true,
            title: "Тестовое поле"      
        },
    }
});
		defineRule("Pressure_Sensors_2_change", {
			  whenChanged: ("wb-mai6_40/IN 2 P Value"),
    			  then: function (newValue) {
                     dev["PressSensors/Press2"] = String(dev["wb-mai6_40/IN 2 P Value"]/1000); 
			  }
			});
		defineRule("Pressure_Sensors_5_change", {
			  whenChanged: ("wb-mai6_40/IN 2 P Value"),
    			  then: function (newValue) {
                     dev["PressSensors/Test"] = String(dev["wb-mai6_40/IN 2 P Value"]/1000); 
			  }
			});
```
В HA проваливается только сенсор "Тестовое поле", у которого тип значения "text" (или можно ставить "value").
Сенсор  "Датчик 2" не проваливается, видимо, из-за несоответствия типов данных. 

Вопрос, можно ли при помощи данного решения отправлять в HA данные типа "pressure"?

**Comment by 4mr** [comment]
Добавил тип "давление" [fdf4286](https://github.com/4mr/wb-engine/commit/fdf4286ccdda89e725b20d23d63df2813827d431)

**Comment by ilttkolosov** [comment]
Спасибо огромное, теперь работает!
![image](https://github.com/user-attachments/assets/9bc8610a-9299-492f-bc99-bac008a3ff1d)
