### ISSUE TITLE
Поддержка авторизации в MQTT

### ISSUE THREAD

**Issue by mirackle-spb** [4mr/wb-engine#27]
Анонимный логин в MQTT не очень чтобы безопасно.
Система позволяет запаролить доступ, но при отключении анонимного доступа - wb-engine-helper вываливается по таймауту, и даже не говорит что у него не получилось.
Хорошо бы как-то реализовать возможность авторизации на MQTT брокере.

**Comment by 4mr** [comment]
Вы можете установить логин на внешний интерфейс, а localhost оставить без пароля, скрипт подключается через localhost.
