### ISSUE TITLE
WB-MRGBW-D регулировка яркости от 0 то 100, а нужно от 0 до 255

### ISSUE THREAD

**Issue by Coriolis-russian** [4mr/wb-engine#3]
При подключении диммера WB-MRGBW-D из HA яркость белого канал регулируется от 0 до 100 (видимо подразумеваются проценты). Однако диммер воспринимает это как абсолютное значение и получается что максимальная яркость ограничена 100.
Надо видимо в конфиг HA передавать параметр brightness_scale равным 255. Ну или не знаю как это разрулить.

**Comment by 4mr** [comment]
Для LED диммера ставится "brightness_scale: 100" (WB работает с цифрами 0 - 100), у меня работает корректно. Посмотрите в HA у устройства MQTT Info , что указано для канала?

**Comment by Coriolis-russian** [comment]
![2022-11-06_18-59-19](https://user-images.githubusercontent.com/7225709/200181124-7ee38809-debb-4b84-a01c-96ef52f0b1ff.png)
Вот такое?

**Comment by Coriolis-russian** [comment]
Я просто в MQTT explorer если ставлю в White/on значение 255 то лента врубается на полную. Ну и видно в WB интерфейсе, там тоже ползунок от 0 до 255. А вот если через эту интеграцию (кстати классно сделано, всё из WB в HA мышкой переносится, жаль раньше не наткнулся, столько вручную вводил) то она яркость делает от 0 до 100, т.е. меньше половины ленты. Я пытаюсь управлять именно W каналом (в WB он отдельным бегунком "белый"), может с этим связано, может как раз не яркость нужна а какой-то спец. канал? Но ведь через эту интеграцию я просто подключил White канал и всё:

![2022-11-06_19-05-09](https://user-images.githubusercontent.com/7225709/200181391-5318b09d-0000-470f-8d7e-ce77c4190910.png)

**Comment by 4mr** [comment]
Можно было текстом.
Вижу что имя устройства переименовано в WB, нужно чтобы было дефолтное, по имени скрипт определяет тип устройства и применяет настройки необходимые. 
Покажите скрин настроек из WB для данного устройства, чтобы видно было какой шаблон? Мне кажется тут еще шаблон какой то другой.

**Comment by 4mr** [comment]
Вот так у меня выглядит LED диммер:
![image](https://user-images.githubusercontent.com/78191171/200181475-7feb7fe9-3a1f-4f4f-9039-f050c16eefed.png)

**Comment by Coriolis-russian** [comment]
![2022-11-06_19-09-50](https://user-images.githubusercontent.com/7225709/200181618-0c0b0edd-4e51-4606-a17f-af235a49af34.png)
![2022-11-06_19-09-04](https://user-images.githubusercontent.com/7225709/200181619-d0e3ae69-0933-4e4c-96a9-6de5639381bc.png)

**Comment by 4mr** [comment]
Идентификатор устройства в MQTT убрать, оставить дефолт, и шаблон вроде обновлялся, у вас какой то старый судя по названиям каналов.

**Comment by Coriolis-russian** [comment]
Я попробую убрать (хотя он красным поле рисует сразу, попробую заново завести устройство.
На счёт обнов - позавчера специально обновил WirenBoard6 через репу, прям 100% всё свежее. Еще и прошивки обновил (какие там смог скрипт, правда сами RGB не обновились почему-то, кстати только сейчас понял)
Вроде при переходе на новую репу (она там с 2021 года у ребят вроде новая) как я понял  шаблоны тоже обновляются все. А само устройство если что старое, года 4 назад покупал только сейчас руки дошли.

**Comment by Coriolis-russian** [comment]
![2022-11-06_19-14-13](https://user-images.githubusercontent.com/7225709/200181851-39650183-cdad-40c1-8f2f-189c0dbbd8df.png)
Есть еще такой в списке, fw3 какой-то, я не понял как смотерть отличия, какой мне выбрать. Попробую потом и его.

**Comment by 4mr** [comment]
> Я попробую убрать (хотя он красным поле рисует сразу, попробую заново завести устройство.

Необходимо убрать галочку нажав на кнопку "Свойства"

**Comment by 4mr** [comment]
> Есть еще такой в списке, fw3 какой-то, я не понял как смотреть отличия, какой мне выбрать. Попробую потом и его.

Вот на основе fw3 я и делал, это новый шаблон, но тут я не могу знать будет ли он совместим с вашим модулем.

**Comment by Coriolis-russian** [comment]
А название же можно оставить своё? А то у меня их 4 всего, запутаюсь.

**Comment by 4mr** [comment]
> А название же можно оставить своё? А то у меня их 4 всего, запутаюсь.

Название да можно, оно используется отображается в интерфейсе WB

**Comment by 4mr** [comment]
Но у вас все равно не заработает, т.к. я с таким шаблоном (устройством) не сталкивался

**Comment by Coriolis-russian** [comment]
Посмотрел в шаблон fw3. ОГО там от моего отличается! Пробую его, надеюсь заработает) Но у меня модуль который когда я еще покупал 4 года назад уже снимали с производства. В общем пробую. Обязательно отпишусь.

**Comment by Coriolis-russian** [comment]
Да, на fw3 моя железка не заработала, увы.
Т.е. ваше решение не для шаблона WB-MRGBW-D (БЕЗ fw3)
Жаль, вручную буду дальше мучаться, что-то не очень получается с яркостью, ну да разберусь.
Спасибо за помощь!

**Comment by 4mr** [comment]
> Да, на fw3 моя железка не заработала, увы. Т.е. ваше решение не для шаблона WB-MRGBW-D (БЕЗ fw3) Жаль, вручную буду дальше мучаться, что-то не очень получается с яркостью, ну да разберусь. Спасибо за помощь!

Ну если вы готовы , можно попробовать для вашей сделать "шаблон".

**Comment by Coriolis-russian** [comment]
Конечно готов! Что от меня требуется?

**Comment by 4mr** [comment]
Я сейчас попробую добавить устройство такое же себе , посмотрю что создается и как управляется. Отпишусь тут.

**Comment by 4mr** [comment]
Добавил, но чтото не вижу как включаться должна лента.
Покажите из MQTT Explorer скрин, чтобы было видно два канала RGB и White. 
+ Скрин из WB из раздела Устройства, с этим диммером. Хочу понять как управляется диммер, у него нету отдельного on/off получается?

**Comment by Coriolis-russian** [comment]
![2022-11-06_19-37-22](https://user-images.githubusercontent.com/7225709/200182972-651ad003-9821-4514-abca-38a4b96fb06f.png)
![2022-11-06_19-38-02](https://user-images.githubusercontent.com/7225709/200183010-e649212c-6c0b-43f3-a3d3-1fe98d18fb75.png)

**Comment by Coriolis-russian** [comment]
У него есть два режима, один который на скринах а второй в котором все три канала отдельно. Но второй режим не интересный да и в нём у меня белый неуправляемый)) Так что наверно имеет смысл только под основной режим.

**Comment by 4mr** [comment]
А как происходит включение отключение ленты?

**Comment by Coriolis-russian** [comment]
Я так понимаю "Белый" в 0 - лента выключается. Ну визуально уж точно - не горит.

**Comment by Coriolis-russian** [comment]
Да, и я пробовал через HA настраивать через light
Там вот если в White писать в значение то ничего не происходит. А вот если в White\on  то как раз и меняет яркость канала "белый".

**Comment by 4mr** [comment]
Попробуйте заменить файл /etc/wb-rules/wb-engine.devices.conf, на этот (надо будет переименовать, не дает закачать сюда .conf файл):
[wb-engine.devices.txt](https://github.com/4mr/wb-engine/files/9946365/wb-engine.devices.txt)

**Comment by Coriolis-russian** [comment]
Ух, долго пробовал, перегружал WB, а то не появлялось устройство. Оставил имя в MQTT по дефолту, если что.
![2022-11-06_20-25-35](https://user-images.githubusercontent.com/7225709/200185459-e520a8dc-7cb5-4532-ac3e-5dedbdbe7dd5.png)
Почему-то теперь вот так стало, раньше хотя бы шкала была а сейчас просто On Off
![2022-11-06_20-25-26](https://user-images.githubusercontent.com/7225709/200185480-47d4c639-9e45-4c93-82bc-de2b4cdc5d42.png)

**Comment by 4mr** [comment]
Кажется победил White и режим "независимые каналы", щас по аналогии попробую RGB и скину файл на тест.

**Comment by Coriolis-russian** [comment]
Ага, моих познаний не хватает что бы понять. "on_command_type": "brightness" вот это у меня не работало когда вручную пытался настроить, поэтому стал искать и наткнулся на ваше решение.
(кстати а прикольно что внешнее устройство через MQTT может так взять и передавать конфиг для HA, во напридумывали)

**Comment by 4mr** [comment]
[wb-engine.devices.txt](https://github.com/4mr/wb-engine/files/9946453/wb-engine.devices.txt)

Обновите файл, удалите из HA устройство. Зайдите в WB и перейдите в настройки WB Engine, включите каналы RGB/White и сохраните. Должно заработать!

**Comment by Coriolis-russian** [comment]
Увы нет, появился RGB но так и как белый до этого - только  switch.
В исходной вашей версии же был бегунок который даже работал (только до 100 максимум). Может как-то откопировать просто и туба добавить что макс. 255? На самом деле я даже теряюсь, а как вы будете различать fw3 и не fw3. 
Да уж, не просто это. Пока гуглю, может мои как-то можно обновить до fw3 (но у меня сомнения, иначе бы не было отдельного шаблона скорее всего)
![2022-11-06_20-56-44](https://user-images.githubusercontent.com/7225709/200186992-5e84032b-7073-4edc-9fb0-8b2ec6081299.png)
![2022-11-06_20-56-36](https://user-images.githubusercontent.com/7225709/200186993-d8f603fa-1dff-45e2-b9ca-02c1d0eee6c0.png)
![2022-11-06_20-56-16](https://user-images.githubusercontent.com/7225709/200186994-d905bd2d-8a2a-4856-9276-ea4583c2600f.png)

**Comment by 4mr** [comment]
Нажмите на иконку лампы слева, должна открыться расширенная конфигурация, и там будет регулировка яркости. Попробуйте включить со стороны ВБ Белый канал, тут я вижу серым, будто ошибка.

**Comment by 4mr** [comment]
![image](https://user-images.githubusercontent.com/78191171/200187301-1edb110c-4b32-49be-bfbf-741bcdd148a9.png)

У меня работает.

**Comment by Coriolis-russian** [comment]
Всё заработало!!! прошло какое-то время, видимо в MQTT топик не сразу обновился!
И всё, всё "чётка")) Спасибо огромное! Это войдёт в релиз или чисто для меня костыль?

**Comment by 4mr** [comment]
[wb-engine.devices.txt](https://github.com/4mr/wb-engine/files/9946497/wb-engine.devices.txt)

Попробуйте эту версию, тут поправил топики у RGB. Но у прошлой Белый канал должен работать нормально.

**Comment by 4mr** [comment]
РГБ у Вас щас управляться не будет, обновите файл. (сделал включение RGB белым цветом 255;255;255)
Да войдет в релиз. По имени mqtt видно что старое устройство (не fw3) и будут применяться правила.

**Comment by Coriolis-russian** [comment]
Ага, всё супер. Большое спасибо! Жаль что я чисто случайно наткнулся на эту интеграцию, удобно ведь, чисто мышкой прощелкать и все устройства заведены в HA.

**Comment by 4mr** [comment]
Повезло наткнуться, я ее выложил на днях буквально. Добавил исправление в релиз новый.
