### ISSUE TITLE
Тип сущностей "Влажность" для wb-msw-v4 не конфигурируется

### ISSUE THREAD

**Issue by Glowar** [4mr/wb-engine#31]
**Добрый день. Спасибо Вам огромное! Очень много времени сэкономили!**

У датчика wb-msw-v4 не указывается state_class и unit_of_measurement.

device:
  identifiers: wb-msw-v4_25
  manufacturer: WirenBoard
  model: wb-msw-v4 [wb-modbus]
  name: WB-MSW v.4 25
availability_mode: latest
enabled_by_default: true
availability:
  - topic: /devices/wb-msw-v4_25/controls/Humidity
    value_template: '{{ False if value == '''' else True }}'
    payload_not_available: false
    payload_available: true
  - topic: /devices/wb-msw-v4_25/controls/Humidity/meta
    value_template: '{{ False if value == '''' else True }}'
    payload_not_available: false
    payload_available: true
  - topic: /devices/wb-msw-v4_25/controls/Humidity/meta/error
    value_template: '{{ True if value == '''' else False }}'
    payload_not_available: false
    payload_available: true
unique_id: wb-msw-v4_25_humidity
object_id: wb-msw-v4_25_humidity
state_topic: /devices/wb-msw-v4_25/controls/Humidity
name: Влажность

![Screenshot 2024-12-11 013608](https://github.com/user-attachments/assets/643801fd-5b89-4d6b-8748-632f601a6fb5)

**Comment by Glowar** [comment]
![image](https://github.com/user-attachments/assets/ed440a7e-35ca-4f0e-ac73-e17826a13788)

**Comment by Glowar** [comment]
![image](https://github.com/user-attachments/assets/d0b590ff-dee0-4e4a-abc9-68b3239c470d)

**Comment by Glowar** [comment]
![image](https://github.com/user-attachments/assets/2dfd8650-3ec2-4767-a11b-ef82d6abaf49)

**Comment by 4mr** [comment]
Проверьте еще правильность шаблона в WB, в настройках wb-mqtt-serial? Или это WB сломали свой же шаблон, в котором type было rel_humidity.

**Comment by 4mr** [comment]
Fixed in [v0.3.12](https://github.com/4mr/wb-engine/releases/tag/v0.3.12)
