### ISSUE TITLE
Правильное отображение цветовой температуры в HA

### ISSUE THREAD

**Issue by Destix** [4mr/wb-engine#4]
Речь пойдет о CCT свете.

С какой-то там версии в HA перешли на Кельвины, и сначала min_mireds: 0 перестали принимать, а теперь и вообще вся шкала съехала. 

Шаблон должен выглядеть приблизительно вот так. Название устройства тестовое, значения mired подобраны для моей ленты, ну и так чтобы 50% попадало в центр шкалы.

```
{
   "device":{
      "manufacturer":"Test",
      "name":"WB-MRGBW-D-fw3 31 test",
      "model":"wb-mrgbw-d-fw3 [wb-modbus]",
      "identifiers":"wb-mrgbw-d-fw3_31 test"
   },
   "name":"31 12 test",
   "object_id":"wb-mrgbw-d-fw3_31_cct1_channels_1_2 test",
   "unique_id":"wb-mrgbw-d-fw3_31_cct1_channels_1_2 test",
   "enabled_by_default":true,

   "availability_mode":"latest",
   "availability":[
      {
         "payload_available":true,
         "payload_not_available":false,
         "value_template":"{{ False if value == '' else True }}",
         "topic":"/devices/wb-mrgbw-d-fw3_31/controls/CCT1 (channels 1_2)"
      },
      {
         "payload_available":true,
         "payload_not_available":false,
         "value_template":"{{ False if value == '' else True }}",
         "topic":"/devices/wb-mrgbw-d-fw3_31/controls/CCT1 (channels 1_2)/meta"
      },
      {
         "payload_available":true,
         "payload_not_available":false,
         "value_template":"{{ True if value == '' else False }}",
         "topic":"/devices/wb-mrgbw-d-fw3_31/controls/CCT1 (channels 1_2)/meta/error"
      }
   ],
   
   "command_topic":"/devices/wb-mrgbw-d-fw3_31/controls/CCT1 (channels 1_2)/on",
   "payload_on":1,
   "payload_off":0,

   "state_topic":"/devices/wb-mrgbw-d-fw3_31/controls/CCT1 (channels 1_2)",

   "brightness_command_topic":"/devices/wb-mrgbw-d-fw3_31/controls/CCT1 Brightness/on",
   "brightness_scale":100,
   "brightness_state_topic":"/devices/wb-mrgbw-d-fw3_31/controls/CCT1 Brightness",

   "min_mireds":227,
   "max_mireds":335,
   "color_temp_state_topic":"/devices/wb-mrgbw-d-fw3_31/controls/CCT1 Temperature",
   "color_temp_value_template":"{{((( value ) * ((this.attributes.max_mireds - this.attributes.min_mireds)/100) ) + this.attributes.min_mireds ) | round(0)}}",
   "color_temp_command_topic":"/devices/wb-mrgbw-d-fw3_31/controls/CCT1 Temperature/on",
   "color_temp_command_template":"{{(( value - this.attributes.min_mireds) / ((this.attributes.max_mireds - this.attributes.min_mireds) / 100) ) | round(0)}}"
}
```

**Comment by 4mr** [comment]
Спасибо за информацию, сделаю возможность указать mireds в форме для каждого канала и добавлю ваш template для преобразования значений.

**Comment by Destix** [comment]
Похоже тут ошибка, статус обратно не считывается.

```
   "color_temp_state_topic":"/devices/wb-mrgbw-d-fw3_31/controls/CCT1 Temperature",
   "color_temp_value_template":"{{((( value ) * ((this.attributes.max_mireds - this.attributes.min_mireds)/100) ) + this.attributes.min_mireds ) | round(0)}}",
```

Посмотрю как время будет.

По майредам:
https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B9%D1%80%D0%B5%D0%B4
 
Там зависимость обратная левая часть слайдера (где теплый свет) это 355 майред, а 227 это правая - холодная

**Comment by Destix** [comment]
ok

**Comment by Destix** [comment]
Ошибка оказалась в типе данных, вот так верно и работает:

`  color_temp_value_template: "{{((( value | float ) * ((this.attributes.max_mireds - this.attributes.min_mireds)/100)) + this.attributes.min_mireds ) | round(0)}}"`

вот часть шаблона про цветовую температуру

```
   "min_mireds":244,
   "max_mireds":334,
   "color_temp_state_topic":"/devices/wb-mrgbw-d-fw3_31/controls/CCT1 Temperature",
   "color_temp_value_template":"{{((( value | float ) * ((this.attributes.max_mireds - this.attributes.min_mireds)/100) ) + this.attributes.min_mireds) | round(0)}}", 
   "color_temp_command_topic":"/devices/wb-mrgbw-d-fw3_31/controls/CCT1 Temperature/on",
   "color_temp_command_template":"{{(( value - this.attributes.min_mireds) / ((this.attributes.max_mireds - this.attributes.min_mireds) / 100) ) | round(0)}}"
}
```

**Comment by 4mr** [comment]
```
"min_mireds":244,
"max_mireds":334,
```
Эти цифры справедливы исключительно для вашей ленты или они универсальны? Как лучше сделать, дать возможность вводить свои цифры в форме?

**Comment by Destix** [comment]
Я подбирал для своей ленты. 
Так чтобы включение теплой и холодной (дневной свет, когда две составляющие на максимум) визиуально была на середине. 

![image](https://user-images.githubusercontent.com/32171782/213102343-3fd128a2-5cc4-45c5-9a04-8d0ea10152c3.png)

Но могу предположить что они универсальны если не обращать внимание на цветовую температуру в Кельвинах в интерфейсе.

**Comment by hACKrus** [comment]
Имею такую же ситуацию на WB-LED в режиме CCT. В HA приходит шкала от голубого до синего.
@4mr какими данными могу помочь, чтобы исправить проблему?

**Comment by hACKrus** [comment]
@Destix подскажете подробнее как настроить? У меня не получается завести, в HA ползунок температуры постоянно сбрасывается на значение равное яркости. Вот мой кусок из wb-engine.devices.conf, значения получил конвертировав значения из документации по ленте:
`                "^CCT1": {"type": "light",
                    "color_temp_state_topic": "{{base_topic}}CCT1 Temperature",
                    "color_temp_command_topic": "{{base_topic}}CCT1 Temperature/on",
                    "color_temp_value_template":"{{((( value | float ) * ((this.attributes.max_mireds - this.attributes.min_mireds)/100) ) + this.attributes.min_mireds) | round(0)}}", 
                    "color_temp_command_template":"{{(( value - this.attributes.min_mireds) / ((this.attributes.max_mireds - this.attributes.min_mireds) / 100) ) | round(0)}}",
                    "brightness_state_topic": "{{base_topic}}CCT1 Brightness",
                    "brightness_command_topic": "{{base_topic}}CCT1 Brightness/on",
                    "brightness_scale": 100,
                    "min_mireds": 154,
                    "max_mireds": 385
                },`

Вот что получает HA:
`min_color_temp_kelvin: 2597
max_color_temp_kelvin: 6493
min_mireds: 154
max_mireds: 385
supported_color_modes:
  - color_temp
color_mode: color_temp
**brightness: 186
color_temp_kelvin: 15625
color_temp: 64**
hs_color:
  - 220.434
  - 29.631
rgb_color:
  - 179
  - 204
  - 255
xy_color:
  - 0.256
  - 0.268
friendly_name: WB-LED 145 Лента CCT1
supported_features: 0`

@4mr значения температуры лучше сделать настраиваемыми.

**Comment by efendizadeh** [comment]
Рабочая версия 

**max_mireds: 400
min_mireds: 154**

Подбирается исключительно по характеристикам самой ленты. Считается по формуле:
**_mireds =  1 000 000 / Kelvin_**

эти параметры лучше настраивать на стороне wb-engine.

`
mqtt:
  - light:
      name: "Light Name -1"
      unique_id: wb-mrgbw-d-fw3_160_cct1_channels_1_2
      object_id: wb-mrgbw-d-fw3_160_cct1_channels_1_2

      availability_mode: latest

      availability:
        - topic: /devices/wb-mrgbw-d-fw3_160/controls/CCT1 (channels 1_2)
          value_template: "{{ False if value == '' else True }}"
          payload_not_available: false
          payload_available: true
        - topic: /devices/wb-mrgbw-d-fw3_160/controls/CCT1 (channels 1_2)/meta
          value_template: "{{ False if value == '' else True }}"
          payload_not_available: false
          payload_available: true
        - topic: /devices/wb-mrgbw-d-fw3_160/controls/CCT1 (channels 1_2)/meta/error
          value_template: "{{ True if value == '' else False }}"
          payload_not_available: false
          payload_available: true

      command_topic: "/devices/wb-mrgbw-d-fw3_160/controls/CCT1 (channels 1_2)/on"
      state_topic: "/devices/wb-mrgbw-d-fw3_160/controls/CCT1 (channels 1_2)"

      brightness_state_topic: /devices/wb-mrgbw-d-fw3_160/controls/CCT1 Brightness
      brightness_command_topic: /devices/wb-mrgbw-d-fw3_160/controls/CCT1 Brightness/on
      brightness_scale: 100

      color_temp_state_topic: /devices/wb-mrgbw-d-fw3_160/controls/CCT1 Temperature
      color_temp_command_topic: /devices/wb-mrgbw-d-fw3_160/controls/CCT1 Temperature/on

      color_temp_value_template: "{{ ((((100 - value | float) / 100) * (this.attributes.max_mireds - this.attributes.min_mireds)) + this.attributes.min_mireds) | round(0) }}"
      color_temp_command_template: "{{ (100 - (((value - this.attributes.min_mireds) / (this.attributes.max_mireds - this.attributes.min_mireds)) * 100)) | round(0) }}"

      #Kelvin to RAD 1000000 / Kelvin
      max_mireds: 400
      min_mireds: 154

      payload_on: 1
      payload_off: 0
`
