### ISSUE TITLE
Недопустимый object_id для устройств: Преобразователь интерфейсов WB-MIO

### ISSUE THREAD

**Issue by Destix** [4mr/wb-engine#5]
Автоматом прокидывается object_id на основе топика
получается что-то типа   "object_id": "wb-mio-gpio_100:3_dir1"
и там используется двоеточие **:**

Вот только HA требует:

> <object_id>: The ID of the device. This is only to allow for separate topics for each device and is not used for the entity_id. The ID of the device must only consist of characters from the character class [a-zA-Z0-9_-] (alphanumerics, underscore and hyphen).

https://www.home-assistant.io/integrations/mqtt#mqtt-discovery

как итог пишет ошибку и не регистрирует устройство.

**Comment by 4mr** [comment]
Вы можете вручную указать id в форме для канала. В следующем обновлении сделаю, чтобы автоматически удалялось.

**Comment by Destix** [comment]
object_id можно поменять если вручную вписать HomeAssistant ID в настройках /etc/wb-rules/wb-engine.conf
но топик с двоеточием ему тоже не нравится :(

**Comment by 4mr** [comment]
Можно тогда пример что получает по MQTT Discovery сам HA, сам json объект как выглядит, попробую себе тестово прокинуть и понять как "победить".

**Comment by 4mr** [comment]
Теперь я понял о каком топике речь, исправлю в ближайшее время.
