### ISSUE TITLE
Как заставить подключаться wb-engine к брокеру с паролем?

### ISSUE THREAD

**Issue by Smitkas** [4mr/wb-engine#7]
Вопрос по запароленому доступу к MQTT брокеру
wb-engine не хочет работать в таком режиме на bullseye при установке в /etc/mosquitto/conf.d/10listeners.conf

```
listener 1883
allow_anonymous false
password_file /etc/mosquitto/passwd/default.conf
```
как заставить подключаться wb-engine к брокеру с паролем?

**Comment by 4mr** [comment]
Отключить пароль для localhost и включить для внешнего:
```
listener 1883 127.0.0.1
allow_anonymous true

listener 1883 192.168.0.2
allow_anonymous false
password_file /etc/mosquitto/passwd/default.conf
```
