### ISSUE TITLE
Режим сенсора движения по бинарным входам модулей WB

### ISSUE THREAD

**Issue by Sanderworlds** [4mr/wb-engine#9]
В развитие функционала:
добавить возможность выполнения действия с реле по событию с одного (нескольких) входов модулей wb
актуально для сторонних датчиков и герконов, которые умеют отдавать только логические 0/1

**Comment by 4mr** [comment]
По сенсору движения, тут все не так просто как хотелось бы. Пока непонятно какой алгоритм был бы идеальным и мог бы учесть все возможные случаи.

**Comment by Sanderworlds** [comment]
> По сенсору движения, тут все не так просто как хотелось бы. Пока непонятно какой алгоритм был бы идеальным и мог бы учесть все возможные случаи.

если идти от простого к сложному, то
сейчас алгоритм срабатывает при заданном значении сенсора движения, то для бинарных входов это значение будет фиксированным. т.е. выбор значения срабатывания в принципе можно убрать. следующее — это сделать возможность инверсии входа 1 = нет движения, 0 = есть движение.
следующий этап - при добавлении второго и следующего триггера входа между ними ставить выбор логической операции и/или

**Comment by 4mr** [comment]
Мне кажется нужно исходить из сценариев использования.
Например датчик движения в душевой + геркон на двери (проводной или zigbee). Необходимо определять наличие человека в помещении, т.к. когда кто-то в душе, то повышается температура и датчик движения уже может не среагировать. Я пока не придумал универсальный алгоритм, но в планах такое есть.

**Comment by hACKrus** [comment]
@4mr Можно ли сделать скрипт, превращающий числовые значения датчика движения в MSW в binary_sensor понятный HA? Выбор current/max motion и порогового значения срабатывания оставить доступным к настройке пользователем.

**Comment by 4mr** [comment]
@hACKrus 

Оно так и реализовано изначально:
![image](https://github.com/4mr/wb-engine/assets/78191171/983bad0d-c7a1-41a9-9cce-1209f83809b3)

В Ха прокидывается в таком виде:

> name: Спальня Движение
> unique_id: motion_11
> object_id: motion_11
> state_topic: /devices/wb-msw-v3_16/controls/Max Motion
> device_class: motion
> payload_on: 'ON'
> payload_off: 'OFF'
> value_template: '{{ (int(value, 0) >= 60) | iif(''ON'', ''OFF'') }}'
> platform: mqtt

**Comment by hACKrus** [comment]
@4mr К сожалению, у меня нет таких опций.
![image](https://github.com/4mr/wb-engine/assets/12397874/3455941c-14be-4b7d-823d-23d9eef72ace)
![image](https://github.com/4mr/wb-engine/assets/12397874/45ab535c-ff67-4d8a-8d9c-3c439b1f7d54)
